services:
  monitor:
    image: monitor-pc:v0.1.5
    container_name: monitor-pc

    environment:
      PORT: ${APP_PORT:-8080}
      PPROF_ENABLED: ${PPROF_ENABLED:-false}
      PPROF_HOST: ${PPROF_HOST:-0.0.0.0}
      PPROF_PORT: ${PPROF_PORT:-6060}

    ports:
      - "${HOST_PORT:-8080}:${APP_PORT:-8080}"
      - "127.0.0.1:${PPROF_PORT:-6060}:${PPROF_PORT:-6060}"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT:-8080}/health"]
      interval: 5s
      timeout: 2s
      retries: 3

    restart: unless-stopped

    mem_limit: 256m
    cpus: 0.5

  client:
    depends_on:
       monitor:
        condition: service_healthy

    image: curlimages/curl

    command: curl http://monitor:${ADD_PORT:-8080}/health


