volumes:
  postgres_data:

networks:
  backend:
      name: monitor-backend
      driver: bridge

services:
  monitor:
    image: monitor-pc:v0.1.8
    container_name: monitor-pc

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      PORT: ${APP_PORT:-8080}
      PPROF_ENABLED: ${PPROF_ENABLED:-false}
      PPROF_HOST: ${PPROF_HOST:-0.0.0.0}
      PPROF_PORT: ${PPROF_PORT:-6060}
      DATABASE_URL: ${DATABASE_URL}

    ports:
      - "${HOST_PORT:-8080}:${APP_PORT:-8080}"
      - "127.0.0.1:${PPROF_PORT:-6060}:${PPROF_PORT:-6060}"

    networks:
      - backend


    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT:-8080}/health"]
      interval: 5s
      timeout: 2s
      retries: 3

    restart: unless-stopped

    mem_limit: 256m
    cpus: 0.5

  client:
    depends_on:
       monitor:
        condition: service_healthy

    image: curlimages/curl

    networks:
      - backend

    command: curl http://monitor:${APP_PORT:-8080}/health

  postgres:
    image: postgres:17-alpine

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: monitor_db

    networks:
      - backend

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d monitor_db"]
      interval: 5s
      timeout: 2s
      retries: 3
    


